### ISSUE TITLE
Unpack error

### ISSUE THREAD

**Issue by malago86** [RaidAndFade/PyCASC#1]
Hello,

Thanks so much for porting a CASC reader to Python!

I am trying to use your script to read data from the Diablo III folder but I am getting the following error:
```
C:\Program Files\Python37\lib\site-packages\PyCASC\utils\CASCUtils.py in _r_casc_dataheader(f)
    143 def _r_casc_dataheader(f):
--> 144     blth,sz,f_0,f_1,chkA,chkB=struct.unpack("16sI2b4s4s",f.read(30))
    145     return blth,sz,f_0,f_1,chkA,chkB
    146 

error: unpack requires a buffer of 30 bytes
```

Also, with I am getting a different error if I try to read the PTR folder:

```
C:\Program Files\Python37\lib\site-packages\PyCASC\utils\CASCUtils.py in parse_root_file(uid, fd, cascreader)
    273         with open(f"{uid}.rootfile","wb+") as f:
    274             f.write(fd)
--> 275         raise Exception(f"Don't know how to read root file for {uid}. Dumped contents to {uid}.rootfile")

Exception: Don't know how to read root file for d3t. Dumped contents to d3t.rootfile
```

How can I do to read these folders? 

Am I missing something here? I hope you can help me :)

**Comment by RaidAndFade** [comment]
First error seems to suggest there is a new casc format, or your data is corrupt.
Second error is due to the fact that this doesn't natively support d3t. You could manually add it in the decoder map



On Thu, May 28, 2020 at 7:16 PM -0400, "malago86" <notifications@github.com> wrote:















Hello,


Thanks so much for porting a CASC reader to Python!


I am trying to use your script to read data from the Diablo III folder but I am getting the following error:
C:\Program Files\Python37\lib\site-packages\PyCASC\utils\CASCUtils.py in _r_casc_dataheader(f)
    143 def _r_casc_dataheader(f):
--> 144     blth,sz,f_0,f_1,chkA,chkB=struct.unpack("16sI2b4s4s",f.read(30))
    145     return blth,sz,f_0,f_1,chkA,chkB
    146 

error: unpack requires a buffer of 30 bytes



Also, with I am getting a different error if I try to read the PTR folder:
C:\Program Files\Python37\lib\site-packages\PyCASC\utils\CASCUtils.py in parse_root_file(uid, fd, cascreader)
    273         with open(f"{uid}.rootfile","wb+") as f:
    274             f.write(fd)
--> 275         raise Exception(f"Don't know how to read root file for {uid}. Dumped contents to {uid}.rootfile")

Exception: Don't know how to read root file for d3t. Dumped contents to d3t.rootfile



How can I do to read these folders?


Am I missing something here? I hope you can help me :)

**Comment by malago86** [comment]
You were totally right! Game was working but some files were corrupted, who knows why... A repair with the Battle.net app fixed it. And I could also add the d3t.

Thanks for your quick response!
